name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  DataStructures_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: cd DataStructures && make test

  FileTransfer_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: cd FileTransfer && make test
