name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  DataStructures_tests:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: cd DataStructures && make test
